[workspace]
members = ["crates/*"]
default-members = ["crates/shottimer-core", "crates/shottimer-app"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Michael Lohr <michael@lohr.dev>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/michidk/shottimer"

[workspace.dependencies]
shottimer-core = { path = "crates/shottimer-core" }
shottimer-app = { path = "crates/shottimer-app" }
embedded-hal = "1.0.0"
embedded-hal-async = "1.0.0"
embassy-futures = "0.1.2"
embedded-graphics = "0.8.1"
gc9a01a_driver = "1.0.0"
heapless = "0.9.1"
libm = "0.2.15"
ph-qmi8658 = { git = "https://github.com/michidk/ph-qmi8658-imu.git", rev = "b91ba41c28a8c3f6d44277567b8ab74b4c583191" }
static_cell = "2.1.1"
u8g2-fonts = "0.8.0"

[profile.dev]
codegen-units = 1
debug = 2
incremental = false
opt-level = "s"

[profile.release]
codegen-units = 1
debug = 2
lto = true
opt-level = "s"
